### ISSUE TITLE
tfjs_graph_converter and/or tensorflow 1.X

### ISSUE THREAD

**Issue by PierreMardon** [ajaichemmanam/simple_bodypix_python#3]
Hi there,
I'm starting an experiment and I'd like to use bodypix in python.
I'm pretty new to python environment so I might get things wrong.
I'm using python 3.7

First, trying to use tfjs_graph_converter, I never get the `api` or `util` members in the debugger. Consequently it crashes. I installed tfjs_graph_converter `1.0.1` using pip.

Then, as I'm starting a new project I would like to install a newer version of all of this, say TF 2.X and TFJS 1.7.4.
Would your code still work, are there "easy" adaptations to make or do you have any recommandation ?

**Comment by ajaichemmanam** [comment]
TF 2.X and TFJS 1.7.4. will work. 
Please install tfjs_graph_converter from https://github.com/ajaichemmanam/tfjs-to-tf
Original repo has some compatibility issues

**Comment by PierreMardon** [comment]
Thank you, it works perfectly with your converter, I wish I had asked earlier ;)
